sudo: required
services: 
  - docker


before_install:
  - docker build -t basha/docker-react-app -f Dockerfile.dev .


script:
  - docker run basha/docker-react-app npm run test -- --coverage --watchAll=false

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-012513289965"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"